> ### Assignment Instructions (delete this cell before submission)
> 
> The objective of this assignment is to develop a solid understanding of PyTorch tensors. In this assignment you will:
>
> 1. Pick 5 interesting functions related to PyTorch tensors by [reading the documentation](https://pytorch.org/docs/stable/torch.html), 
> 2. Edit this starter template notebook to illustrate their usage and publish your notebook to Jovian using `jovian.commit`. Make sure to add proper explanations too, not just code.
> 3. Submit the link to your published notebook on Jovian here: https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor .
> 4. (Optional) Write a blog post on [Medium](https://medium.com) to accompany and showcase your Jupyter notebook. [Embed cells from your notebook](https://medium.com/@aakashns/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e) wherever necessary.
> 5. (Optional) [Share your work](https://jovian.ai/forum/t/pytorch-functions-and-tensor-operations/13790) with the community and exchange feedback with other participants
>
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Colab". Run `jovian.commit` regularly to save your progress.
> 
> Try to give your notebook an interesting title e.g. "All about PyTorch tensor operations", "5 PyTorch functions you didn't know you needed", "A beginner's guide to Autograd in PyToch", "Interesting ways to create PyTorch tensors", "Trigonometic functions in PyTorch", "How to use PyTorch tensors for Linear Algebra" etc.
>
> **IMPORTANT NOTE**: Make sure to submit a Jovian notebook link e.g. https://jovian.ai/aakashns/01-tensor-operations . Colab links will not be accepted.
>
> Remove this cell containing instructions before making a submission or sharing your notebook, to make it more presentable.
>



# Torch Functions
PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.

- torch.eye
- torch.empty
- torch.reshape
- torch.random
- torch.argmax

Before we begin, let's install and import PyTorch

In [1]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [1]:
# Import torch and other required modules
import torch

## Function 1 - torch.eye

Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.

In [2]:
# Example 1 
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

returns a metrics with ones on the diagonal

In [9]:
# Example 2
torch.eye(3, 6)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.]])

input number is the number of rows, and the number of cols

In [10]:
# Example 3 
torch.eye(3, 6, 2)

TypeError: eye() received an invalid combination of arguments - got (int, int, int), but expected one of:
 * (int n, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (int n, int m, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


Only two parameters needed 

Use it  to return a 2-D tensor of size n*m with ones on the diagonal and zeros elsewhere.

Let's save our work using Jovian before continuing.

In [11]:
!pip install jovian --upgrade --quiet

In [12]:
import jovian

In [13]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Creating a new project "catherinedoudou/01-tensor-operations"
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/catherinedoudou/01-tensor-operations


'https://jovian.ai/catherinedoudou/01-tensor-operations'

## Function 2 - torch.empty

Returns a tensor filled with uninitialized data. The shape of the tensor is defined by the variable argument .size

In [15]:
# Example 1 
torch.empty(3, 2)


tensor([[4.4314e-11, 3.0773e-41],
        [3.8791e-11, 3.0773e-41],
        [8.9683e-44, 0.0000e+00]])

returns random data with M number of rows and N number of cols, can be any data types

In [17]:
# Example 2
torch.empty(3, 2, dtype=int)

tensor([[94318258705264, 94318257921008],
        [           112,             64],
        [94318258369872,              0]])

returns specially data type int

In [21]:
# Example 3 - 
torch.empty(-1)

RuntimeError: Trying to create tensor with negative dimension -1: [-1]

parameters must be positive

Closing comments about when to use this function

In [22]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "catherinedoudou/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/catherinedoudou/01-tensor-operations


'https://jovian.ai/catherinedoudou/01-tensor-operations'

## Function 3 - torch.reshape
Returns a tensor with the same data and number of elements as input, but with the specified shape

In [26]:
# Example 1 
a = torch.empty(2, 3)
torch.reshape(a, (3, 2))

tensor([[1.4912e-04, 4.5724e-41],
        [4.1944e-11, 3.0773e-41],
        [4.4842e-44, 0.0000e+00]])

parameters
input (Tensor) – the tensor to be reshaped

shape (tuple of python:ints) – the new shape

In [33]:
# Example 2 
b = torch.arange(4.)
torch.reshape(b, (2, 2))

tensor([[0., 1.],
        [2., 3.]])

from vector reshape to 2*2 metrics

In [36]:
# Example 3 - 
b.reshape(3.)

TypeError: reshape(): argument 'shape' (position 1) must be tuple of ints, not float

reshape(): argument 'shape' (position 1) must be tuple of ints, not float

Closing comments about when to use this function

In [37]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "catherinedoudou/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/catherinedoudou/01-tensor-operations


'https://jovian.ai/catherinedoudou/01-tensor-operations'

## Function 4 - torch.rand

is a package implementing various optimization algorithms.

In [50]:
# Example 1 - 
torch.rand(4, 2)

tensor([[0.1077, 0.2079],
        [0.0064, 0.6744],
        [0.6135, 0.9050],
        [0.1129, 0.1360]])

Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)[0,1)

In [57]:
# Example 2 - 
torch.rand(3, dtype=float)

tensor([0.1281, 0.4510, 0.3703], dtype=torch.float64)

can use argument to define data type

In [58]:
torch.rand(3, dtype=int)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

the number is between 0 and 1, so datatype int is not allowed.

Closing comments about when to use this function

In [18]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 5 - torch.argmax

Returns the indices of the maximum value of all elements in the input tensor

In [71]:
# Example 1 - 
a = torch.rand(10)
torch.argmax(a)

tensor(7)

index for the biggest number in the input

In [79]:
# Example 2 
a = torch.empty(3, 10)
torch.argmax(a, dim=1)

tensor([2, 6, 8])

argument:
dim (int) – the dimension to reduce. If None, the argmax of the flattened input is returned.

In [85]:
# Example 3 
a = torch.arange(3, 10)
torch.argmax(a, dim=1)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

numbers can not be reduced to 1 dimension

In [86]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "catherinedoudou/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/catherinedoudou/01-tensor-operations


'https://jovian.ai/catherinedoudou/01-tensor-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
