> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [20]:
!pip install jovian --upgrade -q

In [21]:
import jovian

In [34]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "catherinedoudou/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/catherinedoudou/numpy-array-operations


'https://jovian.ai/catherinedoudou/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [35]:
import numpy as np

In [38]:
# List of functions explained 
function1 = np.linspace
function2 = np.arange
function3 = np.mean
function4 = np.matmul
function5 = np.split

## Function 1 - np.linspace

Add some explanation about the function in your own words

In [39]:
import numpy as np

Return evenly spaced numbers over a specified interval.

In [40]:
# Example 2 - working
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

Explanation about example

In [41]:
# Example 3 - breaking (to illustrate when it breaks)
np.linspace(1, 100, -1)

ValueError: Number of samples, -1, must be non-negative.

The second argument is Number of samples to generate. Default is 50. Must be non-negative.

Returns num evenly spaced samples can be fast

In [42]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "catherinedoudou/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/catherinedoudou/numpy-array-operations


'https://jovian.ai/catherinedoudou/numpy-array-operations'

## Function 2 - np.arange

In [43]:
# Example 1 - working
np.arange(9,100,9)

array([ 9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

Return evenly spaced values within a given interval.

In [44]:
# Example 2 - working
np.arange(9,1,-0.1)

array([9. , 8.9, 8.8, 8.7, 8.6, 8.5, 8.4, 8.3, 8.2, 8.1, 8. , 7.9, 7.8,
       7.7, 7.6, 7.5, 7.4, 7.3, 7.2, 7.1, 7. , 6.9, 6.8, 6.7, 6.6, 6.5,
       6.4, 6.3, 6.2, 6.1, 6. , 5.9, 5.8, 5.7, 5.6, 5.5, 5.4, 5.3, 5.2,
       5.1, 5. , 4.9, 4.8, 4.7, 4.6, 4.5, 4.4, 4.3, 4.2, 4.1, 4. , 3.9,
       3.8, 3.7, 3.6, 3.5, 3.4, 3.3, 3.2, 3.1, 3. , 2.9, 2.8, 2.7, 2.6,
       2.5, 2.4, 2.3, 2.2, 2.1, 2. , 1.9, 1.8, 1.7, 1.6, 1.5, 1.4, 1.3,
       1.2, 1.1])

return a descending evenly spaced values

In [45]:
# Example 3 - breaking (to illustrate when it breaks)
np.arange(1,8,2,4)

TypeError: Cannot interpret '4' as a data type

The forth argument is datatype

Some closing comments about when to use this function.

In [46]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "catherinedoudou/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/catherinedoudou/numpy-array-operations


'https://jovian.ai/catherinedoudou/numpy-array-operations'

## Function 3 - np.datetime64
Compute the arithmetic mean along the specified axis.

In [85]:
# Example 1 - working
np.datetime64('2021-08-21') - np.datetime64('1995-08-21')

numpy.timedelta64(9497,'D')

In [87]:
##There are two Timedelta units (‘Y’, years and ‘M’, months) which are treated specially, 
#because how much time they represent changes depending on when they are used.##
#While a timedelta day unit is equivalent to 24 hours, 
#there is no way to convert a month unit into days, because different months have different numbers of days.

In [90]:
# Example 3 - breaking (to illustrate when it breaks)
np.datetime64('2021-08-21','2021-09-18','D',)

TypeError: function takes at most 2 arguments (3 given)

function takes at most 2 arguments

calculate how many days are between two dates

In [91]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "catherinedoudou/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/catherinedoudou/numpy-array-operations


'https://jovian.ai/catherinedoudou/numpy-array-operations'

## Function 4 - np.matmul

Matrix product of two arrays.

In [47]:
# Example 1 - working
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

For 2-D arrays it is the matrix product:

In [56]:
# Example 2 - working
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[1, 2],
            [3,2]])
np.matmul(a, b)

array([[1, 2],
       [3, 2]])

For 2-D mixed with 1-D, the result is the usual.

In [64]:
#dot 1 -D 
a = [1,2,3]
b = [2,3,4]
#np.dot(a,b) 
np.matmul(a,b) 2-d


20

In [74]:
a =[[1,2],
    [2,3]]

b =[[2,3],
   [2,3]]
#np.dot(a,b)
np.matmul(a,b)

array([[ 6,  9],
       [10, 15]])

need to be a matrix 

mutiple matrix 

In [32]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "catherinedoudou/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/catherinedoudou/numpy-array-operations


'https://jovian.ai/catherinedoudou/numpy-array-operations'

## Function5 = np.split

In [33]:
# Example 1 - working
x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

Split an array into multiple sub-arrays as views into ary

In [ ]:
# Example 2 - working
 
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('Splitting array into 2 equal parts along axis=0:\n', np.split(x, 2, axis=0))
print('Splitting array into 5 equal parts along axis=1:\n', np.split(x, 5, axis=1))

The code np.split(x, 2, axis=0) has splitted Numpy array x into two equal sub-arrays- [[1, 2, 3, 4, 5]] and [[ 6, 7, 8, 9, 10]]

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [1]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "catherinedoudou/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/catherinedoudou/numpy-array-operations


'https://jovian.ai/catherinedoudou/numpy-array-operations'

In [ ]:
jovian.submit(assignment="zero-to-pandas-a2")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
